package com.nexvary.emergencymesh;

import java.util.HashMap;
import java.util.Map;

public final class UiText {
    private static final Map<String,Map<String,String>> L=new HashMap<>();
    static{
        put("en", new String[][]{{"hero","Field command center"},{"subtitle","Emergency communications without internet"},{"nav","Full navigation"},{"identity","Field identity"},{"callsign","Call sign"},{"role","Role"},{"rescue","Rescue team"},{"encryption","Encryption"},{"nodes","Nodes"},{"pending","Pending"},{"trusted","Trusted"},{"radio","Radio"},{"standby","Standby"},{"sos","SOS Emergency Beacon"},{"sos_hint","Queue a high-priority emergency message for local delivery"},{"back","Back"},{"links","Page links"},{"page_ok","Functional page connected inside Yasli kurt. Back returns to the previous page."},{"integrity","Navigation integrity: PASS"},{"exit_title","Exit Yasli kurt?"},{"exit_msg","Mesh state remains stored locally."},{"cancel","Cancel"},{"exit","Exit"},{"messages","Messages"},{"radar","Radar"},{"map","Map"},{"diagnostics","Diagnostics"},{"profile","Field profile"},{"channels","Channels"},{"settings","Settings"},{"about","About"}});
        put("ar", new String[][]{{"hero","مركز القيادة الميداني"},{"subtitle","اتصالات طوارئ دون إنترنت"},{"nav","التنقل الكامل"},{"identity","الهوية الميدانية"},{"callsign","اسم النداء"},{"role","الدور"},{"rescue","فريق إنقاذ"},{"encryption","التشفير"},{"nodes","العُقد"},{"pending","معلّقة"},{"trusted","موثوقة"},{"radio","الراديو"},{"standby","استعداد"},{"sos","نداء استغاثة SOS"},{"sos_hint","إضافة نداء طوارئ عالي الأولوية إلى قائمة الإرسال المحلية"},{"back","رجوع"},{"links","روابط هذه الصفحة"},{"page_ok","صفحة وظيفية مرتبطة فعليًا داخل تطبيق Yasli kurt. زر الرجوع يعيدك إلى الصفحة السابقة."},{"integrity","سلامة التنقل: ناجح"},{"exit_title","الخروج من Yasli kurt؟"},{"exit_msg","سيستمر حفظ حالة الشبكة محليًا."},{"cancel","إلغاء"},{"exit","خروج"},{"messages","المحادثات"},{"radar","الرادار"},{"map","الخريطة"},{"diagnostics","التشخيص"},{"profile","الملف الميداني"},{"channels","القنوات"},{"settings","الإعدادات"},{"about","حول التطبيق"}});
        put("tr", new String[][]{{"hero","Saha komuta merkezi"},{"subtitle","İnternetsiz acil durum iletişimi"},{"nav","Tam gezinme"},{"identity","Saha kimliği"},{"callsign","Çağrı adı"},{"role","Rol"},{"rescue","Kurtarma ekibi"},{"encryption","Şifreleme"},{"nodes","Düğümler"},{"pending","Bekleyen"},{"trusted","Güvenilir"},{"radio","Radyo"},{"standby","Beklemede"},{"sos","SOS Acil İşaret"},{"sos_hint","Yerel teslimat için yüksek öncelikli acil mesajı sıraya al"},{"back","Geri"},{"links","Sayfa bağlantıları"},{"page_ok","Yasli kurt içinde bağlı işlevsel sayfa. Geri önceki sayfaya döner."},{"integrity","Gezinme bütünlüğü: BAŞARILI"},{"exit_title","Yasli kurt uygulamasından çıkılsın mı?"},{"exit_msg","Mesh durumu yerel olarak saklanır."},{"cancel","İptal"},{"exit","Çıkış"},{"messages","Mesajlar"},{"radar","Radar"},{"map","Harita"},{"diagnostics","Tanılama"},{"profile","Saha profili"},{"channels","Kanallar"},{"settings","Ayarlar"},{"about","Hakkında"}});
        put("es", new String[][]{{"hero","Centro de mando de campo"},{"subtitle","Comunicaciones de emergencia sin Internet"},{"nav","Navegación completa"},{"identity","Identidad de campo"},{"callsign","Indicativo"},{"role","Rol"},{"rescue","Equipo de rescate"},{"encryption","Cifrado"},{"nodes","Nodos"},{"pending","Pendientes"},{"trusted","Confiables"},{"radio","Radio"},{"standby","En espera"},{"sos","Baliza de emergencia SOS"},{"sos_hint","Poner en cola un mensaje de emergencia de alta prioridad"},{"back","Atrás"},{"links","Enlaces de página"},{"page_ok","Página funcional conectada dentro de Yasli kurt. Atrás vuelve a la página anterior."},{"integrity","Integridad de navegación: OK"},{"exit_title","¿Salir de Yasli kurt?"},{"exit_msg","El estado de la malla permanece guardado localmente."},{"cancel","Cancelar"},{"exit","Salir"},{"messages","Mensajes"},{"radar","Radar"},{"map","Mapa"},{"diagnostics","Diagnóstico"},{"profile","Perfil de campo"},{"channels","Canales"},{"settings","Ajustes"},{"about","Acerca de"}});
        put("de", new String[][]{{"hero","Feldkommandozentrale"},{"subtitle","Notfallkommunikation ohne Internet"},{"nav","Vollständige Navigation"},{"identity","Feldidentität"},{"callsign","Rufzeichen"},{"role","Rolle"},{"rescue","Rettungsteam"},{"encryption","Verschlüsselung"},{"nodes","Knoten"},{"pending","Ausstehend"},{"trusted","Vertrauenswürdig"},{"radio","Funk"},{"standby","Bereit"},{"sos","SOS-Notrufsignal"},{"sos_hint","Hochpriorisierte Notfallnachricht lokal einreihen"},{"back","Zurück"},{"links","Seitenlinks"},{"page_ok","Funktionale Seite in Yasli kurt. Zurück führt zur vorherigen Seite."},{"integrity","Navigationsintegrität: OK"},{"exit_title","Yasli kurt beenden?"},{"exit_msg","Der Mesh-Status bleibt lokal gespeichert."},{"cancel","Abbrechen"},{"exit","Beenden"},{"messages","Nachrichten"},{"radar","Radar"},{"map","Karte"},{"diagnostics","Diagnose"},{"profile","Feldprofil"},{"channels","Kanäle"},{"settings","Einstellungen"},{"about","Über"}});
        put("it", new String[][]{{"hero","Centro di comando sul campo"},{"subtitle","Comunicazioni di emergenza senza Internet"},{"nav","Navigazione completa"},{"identity","Identità sul campo"},{"callsign","Nominativo"},{"role","Ruolo"},{"rescue","Squadra di soccorso"},{"encryption","Crittografia"},{"nodes","Nodi"},{"pending","In attesa"},{"trusted","Attendibili"},{"radio","Radio"},{"standby","Standby"},{"sos","Segnale di emergenza SOS"},{"sos_hint","Accoda un messaggio di emergenza ad alta priorità"},{"back","Indietro"},{"links","Collegamenti pagina"},{"page_ok","Pagina funzionale collegata in Yasli kurt. Indietro torna alla pagina precedente."},{"integrity","Integrità navigazione: OK"},{"exit_title","Uscire da Yasli kurt?"},{"exit_msg","Lo stato mesh resta salvato localmente."},{"cancel","Annulla"},{"exit","Esci"},{"messages","Messaggi"},{"radar","Radar"},{"map","Mappa"},{"diagnostics","Diagnostica"},{"profile","Profilo sul campo"},{"channels","Canali"},{"settings","Impostazioni"},{"about","Info"}});
        put("fr", new String[][]{{"hero","Centre de commandement terrain"},{"subtitle","Communications d’urgence sans Internet"},{"nav","Navigation complète"},{"identity","Identité terrain"},{"callsign","Indicatif"},{"role","Rôle"},{"rescue","Équipe de secours"},{"encryption","Chiffrement"},{"nodes","Nœuds"},{"pending","En attente"},{"trusted","Fiables"},{"radio","Radio"},{"standby","Veille"},{"sos","Balise d’urgence SOS"},{"sos_hint","Mettre en file un message d’urgence prioritaire"},{"back","Retour"},{"links","Liens de page"},{"page_ok","Page fonctionnelle reliée dans Yasli kurt. Retour revient à la page précédente."},{"integrity","Intégrité navigation : OK"},{"exit_title","Quitter Yasli kurt ?"},{"exit_msg","L’état mesh reste stocké localement."},{"cancel","Annuler"},{"exit","Quitter"},{"messages","Messages"},{"radar","Radar"},{"map","Carte"},{"diagnostics","Diagnostic"},{"profile","Profil terrain"},{"channels","Canaux"},{"settings","Paramètres"},{"about","À propos"}});
        put("ur", new String[][]{{"hero","فیلڈ کمانڈ سینٹر"},{"subtitle","انٹرنیٹ کے بغیر ہنگامی رابطہ"},{"nav","مکمل نیویگیشن"},{"identity","فیلڈ شناخت"},{"callsign","کال سائن"},{"role","کردار"},{"rescue","ریسکیو ٹیم"},{"encryption","خفیہ کاری"},{"nodes","نوڈز"},{"pending","زیر التوا"},{"trusted","قابل اعتماد"},{"radio","ریڈیو"},{"standby","تیار"},{"sos","SOS ہنگامی بیکن"},{"sos_hint","اعلی ترجیحی ہنگامی پیغام قطار میں شامل کریں"},{"back","واپس"},{"links","صفحہ روابط"},{"page_ok","Yasli kurt میں فعال منسلک صفحہ۔ واپس پچھلے صفحے پر لے جاتا ہے۔"},{"integrity","نیویگیشن سالمیت: کامیاب"},{"exit_title","Yasli kurt سے باہر نکلیں؟"},{"exit_msg","Mesh حالت مقامی طور پر محفوظ رہے گی۔"},{"cancel","منسوخ"},{"exit","خروج"},{"messages","پیغامات"},{"radar","ریڈار"},{"map","نقشہ"},{"diagnostics","تشخیص"},{"profile","فیلڈ پروفائل"},{"channels","چینلز"},{"settings","ترتیبات"},{"about","متعلق"}});
        put("fa", new String[][]{{"hero","مرکز فرماندهی میدانی"},{"subtitle","ارتباط اضطراری بدون اینترنت"},{"nav","ناوبری کامل"},{"identity","هویت میدانی"},{"callsign","نام فراخوان"},{"role","نقش"},{"rescue","تیم نجات"},{"encryption","رمزگذاری"},{"nodes","گره‌ها"},{"pending","در انتظار"},{"trusted","مطمئن"},{"radio","رادیو"},{"standby","آماده"},{"sos","چراغ اضطراری SOS"},{"sos_hint","پیام اضطراری با اولویت بالا را در صف قرار دهید"},{"back","بازگشت"},{"links","پیوندهای صفحه"},{"page_ok","صفحه کاربردی متصل در Yasli kurt. بازگشت به صفحه قبل می‌رود."},{"integrity","یکپارچگی ناوبری: موفق"},{"exit_title","خروج از Yasli kurt؟"},{"exit_msg","وضعیت Mesh به‌صورت محلی ذخیره می‌شود."},{"cancel","لغو"},{"exit","خروج"},{"messages","پیام‌ها"},{"radar","رادار"},{"map","نقشه"},{"diagnostics","عیب‌یابی"},{"profile","پروفایل میدانی"},{"channels","کانال‌ها"},{"settings","تنظیمات"},{"about","درباره"}});
        put("ru", new String[][]{{"hero","Полевой командный центр"},{"subtitle","Экстренная связь без Интернета"},{"nav","Полная навигация"},{"identity","Полевая идентификация"},{"callsign","Позывной"},{"role","Роль"},{"rescue","Спасательная команда"},{"encryption","Шифрование"},{"nodes","Узлы"},{"pending","Ожидают"},{"trusted","Доверенные"},{"radio","Радио"},{"standby","Ожидание"},{"sos","Аварийный маяк SOS"},{"sos_hint","Поставить приоритетное аварийное сообщение в очередь"},{"back","Назад"},{"links","Ссылки страницы"},{"page_ok","Функциональная страница подключена в Yasli kurt. Назад возвращает на предыдущую страницу."},{"integrity","Целостность навигации: OK"},{"exit_title","Выйти из Yasli kurt?"},{"exit_msg","Состояние mesh сохранится локально."},{"cancel","Отмена"},{"exit","Выйти"},{"messages","Сообщения"},{"radar","Радар"},{"map","Карта"},{"diagnostics","Диагностика"},{"profile","Полевой профиль"},{"channels","Каналы"},{"settings","Настройки"},{"about","О приложении"}});
    }
    private static void put(String code,String[][] rows){ Map<String,String> m=new HashMap<>(); for(String[] r:rows)m.put(r[0],r[1]); L.put(code,m); }
    public static String t(String code,String key){ Map<String,String> m=L.get(code); if(m==null)m=L.get("en"); String v=m.get(key); if(v==null)v=L.get("en").get(key); return v==null?key:v; }
    private UiText(){}
}
