plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexvary.emergencymesh'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nexvary.emergencymesh'
        minSdk 26
        targetSdk 35
        versionCode 1050
        versionName '2.1.0-stage1050'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
